config/routes.rb
MobilePoc::Application.routes.draw do
  resources :lops

  resources :users

  root :to => 'users#index'

end

app/models/lop.rb
class Lop < ActiveRecord::Base
has_draft
validates_presence_of :name,:description
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  protect_from_forgery
  has_mobile_fu
  before_filter :is_mobile_device? 

end

app/controllers/lops_controller.rb
class LopsController < ApplicationController
  # GET /lops
  # GET /lops.json
  def index
    @lops = Lop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lops }
    end
  end

  # GET /lops/1
  # GET /lops/1.json
  def show
    @lop = Lop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @lop }
    end
  end

  # GET /lops/new
  # GET /lops/new.json
  def new
    @lop = Lop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @lop }
    end
  end

  # GET /lops/1/edit
  def edit
    @lop = Lop.find(params[:id])
  end

  # POST /lops
  # POST /lops.json
  def create
  p "@@@@@@@@@@@@@@@@@@@@@@@@@@#{params[:commit].inspect}"
    @lop = Lop.new(params[:lop])
    if params[:commit] == "Save as Draft"
    @lop.save(:validate => false)
    @lop.instantiate_draft!
    respond_to do |format|
    format.html { redirect_to @lop, :notice => 'Draft Saved Succesfully' }
    end
    else
    respond_to do |format|
      if @lop.save
        format.html { redirect_to @lop, :notice => 'User was successfully created.' }
        format.json { render :json => @lop, :status => :created, :location => @lop }
      else
        format.html { render :action => "new" }
        format.json { render :json => @lop.errors, :status => :unprocessable_entity }
      end
    end
    end
   
  end

  # PUT /lops/1
  # PUT /lops/1.json
  def update
    @lop = Lop.find(params[:id])
     if @lop.has_draft?
       @lop.draft.update_attributes(params[:lop])
        @lop.replace_with_draft!
        @lop.destroy_draft!
        respond_to do |format|
        format.html { redirect_to @lop, :notice => 'Lop was successfully updated.' }
        end
        else
        respond_to do |format|
      if @lop.update_attributes(params[:lop])
        format.html { redirect_to @lop, :notice => 'Lop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @lop.errors, :status => :unprocessable_entity }
      end
    end
        end
    
  end

  # DELETE /lops/1
  # DELETE /lops/1.json
  def destroy
    @lop = Lop.find(params[:id])
    @lop.destroy

    respond_to do |format|
      format.html { redirect_to lops_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
      format.mobile
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lops_helper.rb
module LopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobilePoc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lops/_form.html.erb
<%= form_for(@lop) do |f| %>
  <% if @lop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lop.errors.count, "error") %> prohibited this lop from being saved:</h2>

      <ul>
      <% @lop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= f.submit "Save as Draft" %>
  </div>
<% end %>

app/views/lops/edit.html.erb
<h1>Editing lop</h1>

<%= render 'form' %>

<%= link_to 'Show', @lop %> |
<%= link_to 'Back', lops_path %>

app/views/lops/index.html.erb
<h1>Listing lops</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lops.each do |lop| %>
  <tr>
    <td><%= lop.name %></td>
    <td><%= lop.description %></td>
    <td><%= link_to 'Show', lop %></td>
    <td><%= link_to 'Edit', edit_lop_path(lop) %></td>
    <td><%= link_to 'Destroy', lop, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lop', new_lop_path %>

app/views/lops/new.html.erb
<h1>New lop</h1>

<%= render 'form' %>

<%= link_to 'Back', lops_path %>

app/views/lops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lop.name %>
</p>

<p>
  <b>Description:</b>
  <%= @lop.description %>
</p>


<%= link_to 'Edit', edit_lop_path(@lop) %> |
<%= link_to 'Back', lops_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/index.mobile.erb
in i phone

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>